### ISSUE TITLE
Y/Y8 give 4:2:0 output!

### ISSUE THREAD

**Issue by realfinder** [HomeOfAviSynthPlusEvolution/neo_TMedian#2]
```
ColorBars(width=640, height=480, pixel_type="yv16")
ConvertToY8
neo_tmedian
```

also maybe it's time to update like this https://github.com/HomeOfAviSynthPlusEvolution/neo_DFTTest/pull/3

**Comment by Asd-g** [comment]
The issue with Y clips was already fixed.
Frame properties were fine too (not nuked) because here the source clip is copied as destination. Updated dual synth wrapper for consistency.

**Comment by realfinder** [comment]
thanks Asd-g!
